server:
  port: 9000

app:
  jwt:
    secret: "YourBase64EncodedSecretThatIsAtLeast64BytesLongWhenDecodedFromBase64Format=="
    expiration-ms: "86400000"
  cors:
    allowed-origins:
      - http://localhost:8080
      - http://localhost:8081

spring:
  application:
    name: "exercies"

  datasource:
      username: "belajar_jdbc"
      password: "belajar_jdbc"
      jdbc-url: "jdbc:mysql://localhost:4001/belajar_jdbc"
      maximum-pool-size: "30"

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


logging.level:
  org.springframework.security: TRACE
  org.springframework.web: TRACE
  org.springframework.jdbc: DEBUG